ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER webtour_user CASCADE;
CREATE USER webtour_user IDENTIFIED BY webtour_password DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT DBA TO webtour_user;
EXIT;
