-- SCRIPT NÂNG CẤP ORACLE: AUDIT TRAIL & STORED PROCEDURE
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- ==== 1. AUDIT TRAIL: BẢNG NHẬT KÝ THAY ĐỔI ============
CREATE TABLE "BOOKING_AUDIT" (
    "AUDIT_ID" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BOOKING_ID" NUMBER(10),
    "ACTION" VARCHAR2(50),
    "OLD_PRICE" NUMBER(18,2),
    "NEW_PRICE" NUMBER(18,2),
    "MODIFIED_BY" VARCHAR2(100),
    "MODIFIED_DATE" TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP
);

-- Trigger ghi nhật ký khi Sửa hoặc Xóa Booking
CREATE OR REPLACE TRIGGER TRG_AUDIT_BOOKING
AFTER UPDATE OR DELETE ON "BOOKINGS"
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        INSERT INTO "BOOKING_AUDIT" ("BOOKING_ID", "ACTION", "OLD_PRICE", "NEW_PRICE", "MODIFIED_BY")
        VALUES (:OLD."ID", 'UPDATE', :OLD."TOTAL_PRICE", :NEW."TOTAL_PRICE", USER);
    ELSIF DELETING THEN
        INSERT INTO "BOOKING_AUDIT" ("BOOKING_ID", "ACTION", "OLD_PRICE", "NEW_PRICE", "MODIFIED_BY")
        VALUES (:OLD."ID", 'DELETE', :OLD."TOTAL_PRICE", NULL, USER);
    END IF;
END;
/

-- ==== 2. STORED PROCEDURE: TÍNH GIÁ TOUR =============
-- Thủ tục này giúp C# không cần tự nhân số tiền, đảm bảo tính nhất quán
CREATE OR REPLACE PROCEDURE PROC_CALCULATE_PRICE (
    p_tour_id IN NUMBER,
    p_people IN NUMBER,
    p_is_group IN NUMBER,
    p_total_price OUT NUMBER
) AS
    v_unit_price NUMBER;
BEGIN
    -- Lấy đơn giá từ bảng Tours
    SELECT CASE WHEN p_is_group = 1 THEN "PriceGroup" ELSE "PriceIndividual" END
    INTO v_unit_price
    FROM "Tours"
    WHERE "Id" = p_tour_id;

    -- Tính tổng tiền
    p_total_price := v_unit_price * p_people;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_total_price := 0;
END;
/

SHOW ERRORS;
PROMPT ==== ĐẠI TU ORACLE THÀNH CÔNG: ĐÃ CÓ AUDIT VÀ STORED PROCEDURE ====;
EXIT;
