// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using webtour.Data;

#nullable disable

namespace webtour.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webtour.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BOOKING_DATE");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CUSTOMER_EMAIL");

                    b.Property<string>("CustomerName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<int>("IsGroup")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_GROUP");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMBER_OF_PEOPLE");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.Property<int>("TourId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOUR_ID");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("BOOKINGS");
                });

            modelBuilder.Entity("webtour.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attractions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DurationNights")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("PriceGroup")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal>("PriceIndividual")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("webtour.Models.Booking", b =>
                {
                    b.HasOne("webtour.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });
#pragma warning restore 612, 618
        }
    }
}
